// ============================================================
// AdvancedProgressionSystems.cs — advanced progression systems
// UnityEngine-free
// ============================================================
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Xiuxian.Data;

namespace Xiuxian.Systems
{
    public class ProgressionResult { public Player Player; public bool Success, Triggered, Completed; public string Message, Alignment, Title; public readonly List<string> Logs = new(); }
    public sealed class PvpResult : ProgressionResult { public PvpDuelRecord Record; public CombatResult CombatResult; }
    public sealed class AscensionStatus { public bool CanAscend, ExpReady, IsLooseImmortal; public AscensionDef AscDef; public readonly List<string> Missing = new(); }
    public sealed class AscensionResult : ProgressionResult { public bool TriggerTribulation; public string TribulationId; public AscensionDef AscDef; }
    public sealed class ReincarnationCheck { public bool CanReincarnate; public string Reason, Context; public double Multiplier; public ReincarnationLegacy LegacyPreview, LegacyDelta; }
    public sealed class ReincarnationResult { public Player NewPlayer; public readonly List<string> Logs = new(); public LegacySnapshot LegacySnapshot; }

    internal static class ProgressionUtil
    {
        public static string Alignment(int karma) => karma >= 30 ? "righteous" : karma <= -30 ? "evil" : "neutral";
        public static int Clamp(int v, int min, int max) => Math.Max(min, Math.Min(max, v));
        public static double Round2(double v) => Math.Round(v * 100) / 100.0;
        public static bool CheckCondition(Player p, JToken cond)
        {
            if (cond == null || cond.Type == JTokenType.Null) return true;
            string field = (string)cond["field"], op = (string)cond["op"] ?? ">=";
            int left = field == "tracking.defeatedHigherRealm" ? (p.Tracking.DefeatedHigherRealm ? 1 : 0) : field == "tracking.killCount" ? p.Tracking.KillCount : field == "tracking.bossKillCount" ? p.Tracking.BossKillCount : field == "realmIndex" ? p.RealmIndex : field == "karma" ? p.Karma : p.Gold;
            var val = cond["value"]; int right = val?.Type == JTokenType.Boolean ? (val.Value<bool>() ? 1 : 0) : (val?.Value<int?>() ?? 0);
            return op == "==" ? left == right : op == "<=" ? left <= right : op == "<" ? left < right : op == ">" ? left > right : left >= right;
        }
        public static void AddStat(Player p, string key, double value)
        {
            int iv = (int)Math.Round(value);
            switch (key) { case "maxHp": case "hp": p.MaxHp += iv; p.Hp += iv; break; case "maxMp": case "mp": p.MaxMp += iv; p.Mp += iv; break; case "maxStamina": p.MaxStamina += iv; p.Stamina += iv; break; case "maxMentalPower": p.MaxMentalPower += iv; p.MentalPower += iv; break; case "atk": p.Atk += iv; break; case "def": p.Def += iv; break; case "speed": p.Speed += iv; break; case "luck": p.Luck += iv; break; case "comprehension": p.Comprehension += iv; break; case "charisma": p.Charisma += iv; break; case "lifespan": p.Lifespan += iv; break; case "inventoryCapacity": p.InventoryCapacity += iv; break; case "maxPhysique": p.MaxPhysique += iv; break; case "critRate": p.CritRate += value; break; case "critDmgMultiplier": p.CritDmgMultiplier += value; break; case "critResist": p.CritResist += value; break; case "moveSpeed": p.MoveSpeed += value; break; case "physiqueDmgReduce": p.PhysiqueDmgReduce += value; break; }
        }
        public static double GetStat(Player p, string key) => key == "maxHp" ? p.MaxHp : key == "maxMp" ? p.MaxMp : key == "atk" ? p.Atk : key == "def" ? p.Def : key == "speed" ? p.Speed : key == "maxStamina" ? p.MaxStamina : key == "maxMentalPower" ? p.MaxMentalPower : 0;
        public static void SetStat(Player p, string key, double value) { int iv = (int)Math.Round(value); if (key == "maxHp") p.MaxHp = iv; else if (key == "maxMp") p.MaxMp = iv; else if (key == "atk") p.Atk = iv; else if (key == "def") p.Def = iv; else if (key == "speed") p.Speed = iv; else if (key == "maxStamina") p.MaxStamina = iv; else if (key == "maxMentalPower") p.MaxMentalPower = iv; }
    }

    public static class DestinySystem
    {
        public static readonly List<DestinyDefRuntime> CoreDestinies = new(); public static readonly List<TalentDefRuntime> CoreTalents = new(); public static readonly List<TalentTreeNodeDefRuntime> CoreTalentNodes = new();
        static DestinySystem()
        {
            AddD("core:lone_star",18,-10,e=>{e.StatBonuses["atk"]=4;e.StatBonuses["critRate"]=3;e.CultivationSpeedBonus=.04;}); AddD("core:ziwei_emperor",6,10,e=>{foreach(var k in new[]{"maxHp","maxMp","atk","def","speed"})e.StatMultipliers[k]=.05;e.CultivationSpeedBonus=.06;e.BreakthroughRateBonus=.03;}); AddD("core:immortal_body",6,0,e=>{e.StatMultipliers["maxHp"]=.12;e.StatMultipliers["def"]=.08;e.StatBonuses["maxPhysique"]=20;e.StatBonuses["physiqueDmgReduce"]=2;}); AddD("core:bodhi_heart",20,8,e=>{e.CultivationSpeedBonus=.08;e.BreakthroughRateBonus=.02;}); AddD("core:hidden_dragon",50,0,e=>{e.CultivationSpeedBonus=.03;e.BreakthroughRateBonus=.01;});
            AddT("core:breath_micro",e=>e.CultivationSpeedBonus=.08); AddT("core:sturdy_bones",e=>{e.StatBonuses["maxHp"]=20;e.StatBonuses["def"]=2;}); AddT("core:clear_mind",e=>e.BreakthroughRateBonus=.03); AddT("core:first_edge",e=>{e.StatBonuses["atk"]=5;e.StatBonuses["critRate"]=2;}); AddT("core:wind_step",e=>{e.StatBonuses["speed"]=4;e.StatBonuses["moveSpeed"]=4;}); AddT("core:deep_fortune",e=>e.BreakthroughRateBonus=.04); AddT("core:spirit_vessel",e=>{e.StatBonuses["maxMp"]=25;e.StatBonuses["maxMentalPower"]=10;}); AddT("core:star_blessing",e=>{foreach(var k in new[]{"maxHp","maxMp","atk","def","speed"})e.StatMultipliers[k]=.04;e.CultivationSpeedBonus=.05;e.BreakthroughRateBonus=.02;});
            Node("core:node_breath","core:breath_micro",1,1); Node("core:node_sturdy","core:sturdy_bones",1,1); Node("core:node_edge","core:first_edge",2,1,"core:node_sturdy"); Node("core:node_wind","core:wind_step",2,1,"core:node_breath"); Node("core:node_mind","core:clear_mind",2,1,"core:node_breath");
        }
        static void AddD(string id,int w,int k,Action<StatEffect> f){var e=new StatEffect();f(e);CoreDestinies.Add(new DestinyDefRuntime{Id=id,Name=id,Rarity="core",Weight=w,InitialKarma=k,Effect=e});}
        static void AddT(string id,Action<StatEffect> f){var e=new StatEffect();f(e);CoreTalents.Add(new TalentDefRuntime{Id=id,Name=id,Effect=e});}
        static void Node(string id,string t,int tier,int cost,params string[] pre){var n=new TalentTreeNodeDefRuntime{Id=id,TalentId=t,Tier=tier,Cost=cost};n.PrereqNodeIds.AddRange(pre);CoreTalentNodes.Add(n);}
        public static DestinyTalentState GetState(Player p)=>WorldState.Get(p,"destiny",()=>new DestinyTalentState());
        public static string RollDestinyId(IRng rng){int total=CoreDestinies.Sum(d=>d.Weight);double roll=rng.NextDouble()*total;foreach(var d in CoreDestinies){roll-=d.Weight;if(roll<=0)return d.Id;}return CoreDestinies.Last().Id;}
        public static ProgressionResult EnsureDestiny(Player p,IRng rng){var s=GetState(p);if(string.IsNullOrEmpty(p.DestinyId)){p.DestinyId=RollDestinyId(rng);var d=CoreDestinies.First(x=>x.Id==p.DestinyId);p.Karma=ProgressionUtil.Clamp(p.Karma+d.InitialKarma,-100,100);}foreach(var id in p.TalentIds)if(!s.AcquiredTalentIds.Contains(id))s.AcquiredTalentIds.Add(id);ApplyEffectsToPlayer(p,GetEffects(p));p.Passives["progression.destiny"]=GetEffects(p).CultivationSpeedBonus;return new ProgressionResult{Player=p,Success=true,Message=p.DestinyId};}
        public static void GrantTalentPoints(Player p,int pts)=>GetState(p).TalentPoints+=pts;
        public static ProgressionResult UnlockTalentNode(Player p,string nodeId){var s=GetState(p);var n=CoreTalentNodes.FirstOrDefault(x=>x.Id==nodeId);if(n==null||s.UnlockedNodeIds.Contains(nodeId)||s.TalentPoints<n.Cost||n.PrereqNodeIds.Any(id=>!s.UnlockedNodeIds.Contains(id)))return new ProgressionResult{Player=p,Success=false};s.TalentPoints-=n.Cost;s.UnlockedNodeIds.Add(nodeId);if(!s.AcquiredTalentIds.Contains(n.TalentId))s.AcquiredTalentIds.Add(n.TalentId);if(!p.TalentIds.Contains(n.TalentId))p.TalentIds.Add(n.TalentId);ApplyEffectsToPlayer(p,GetEffects(p));return new ProgressionResult{Player=p,Success=true,Message=n.TalentId};}
        public static StatEffect GetEffects(Player p){var m=new StatEffect();void Merge(StatEffect e){foreach(var kv in e.StatBonuses)m.StatBonuses[kv.Key]=(m.StatBonuses.TryGetValue(kv.Key,out var v)?v:0)+kv.Value;foreach(var kv in e.StatMultipliers)m.StatMultipliers[kv.Key]=(m.StatMultipliers.TryGetValue(kv.Key,out var v)?v:0)+kv.Value;m.CultivationSpeedBonus+=e.CultivationSpeedBonus;m.BreakthroughRateBonus+=e.BreakthroughRateBonus;}var d=CoreDestinies.FirstOrDefault(x=>x.Id==p.DestinyId);if(d!=null)Merge(d.Effect);foreach(var id in GetState(p).AcquiredTalentIds.Concat(p.TalentIds).Distinct()){var t=CoreTalents.FirstOrDefault(x=>x.Id==id);if(t!=null)Merge(t.Effect);}return m;}
        public static void ApplyEffectsToPlayer(Player p,StatEffect e){foreach(var kv in e.StatBonuses)ProgressionUtil.AddStat(p,kv.Key,kv.Value);foreach(var kv in e.StatMultipliers)ProgressionUtil.SetStat(p,kv.Key,ProgressionUtil.GetStat(p,kv.Key)*(1+kv.Value));}
    }

    public static class EnlightenmentSystem
    {
        public const int EnlightenmentPointExp=100,ContemplateCost=1; public static readonly List<EnlightenmentInsightDefRuntime> Insights=new();
        static EnlightenmentSystem(){Insight("core:heaven_mind","any",1,e=>{e.CultivationSpeedBonus=.05;e.BreakthroughRateBonus=.02;});Insight("core:righteous_insight","righteous",1,e=>e.StatBonuses["charisma"]=2);Insight("core:evil_insight","evil",1,e=>e.StatBonuses["atk"]=3);Insight("core:neutral_insight","neutral",1,e=>e.StatBonuses["luck"]=2);}
        static void Insight(string id,string route,int req,Action<StatEffect> f){var e=new StatEffect();f(e);Insights.Add(new EnlightenmentInsightDefRuntime{Id=id,Name=id,Route=route,RequiredInsight=req,Effect=e});}
        public static EnlightenmentState GetState(Player p)=>WorldState.Get(p,"enlightenment",()=>new EnlightenmentState());
        public static ProgressionResult GainComprehension(Player p,int baseGain){var s=GetState(p);int gain=Math.Max(1,(int)Math.Floor(baseGain*(1+p.Comprehension/200.0)));int total=s.ComprehensionExp+gain,pts=total/EnlightenmentPointExp;s.ComprehensionExp=total%EnlightenmentPointExp;s.InsightPoints+=pts;var r=new ProgressionResult{Player=p,Success=true};r.Logs.Add($"comprehension+{gain}");return r;}
        public static ProgressionResult TryTrigger(Player p,int expGain,IRng rng,bool force=false){var s=GetState(p);string a=ProgressionUtil.Alignment(p.Karma);double chance=force?1:(a=="righteous"?.08:a=="evil"?.04:.06)+Math.Min(.06,p.Comprehension/2500.0);if(!force&&rng.NextDouble()>=chance)return new ProgressionResult{Player=p};var defs=Insights.Where(d=>(d.Route=="any"||d.Route==a)&&!s.UnlockedInsightIds.Contains(d.Id)).ToList();if(defs.Count==0)defs=Insights;var def=defs[Math.Min(defs.Count-1,rng.NextIntInclusive(0,defs.Count-1))];double mult=a=="evil"?2.4:a=="righteous"?1.35:1.75;p.Exp+=Math.Max(5,(int)Math.Floor(expGain*mult*(1+s.InsightPoints*.04)));s.ActiveBuffs.Add(new EnlightenmentBuff{Id=$"buff:{p.Age}:{s.TotalTriggers+1}",Name=def.Name,RemainingMonths=a=="evil"?2:3,Effect=def.Effect});while(s.ActiveBuffs.Count>3)s.ActiveBuffs.RemoveAt(0);s.LastEventAge=p.Age;s.TotalTriggers++;return new ProgressionResult{Player=p,Triggered=true,Success=true,Message=def.Id};}
        public static ProgressionResult ContemplateInsight(Player p){var s=GetState(p);if(s.InsightPoints<ContemplateCost)return new ProgressionResult{Player=p,Success=false};string a=ProgressionUtil.Alignment(p.Karma);var t=Insights.FirstOrDefault(d=>!s.UnlockedInsightIds.Contains(d.Id)&&s.InsightPoints>=d.RequiredInsight&&(d.Route=="any"||d.Route==a));if(t==null)return new ProgressionResult{Player=p,Success=false};s.InsightPoints-=ContemplateCost;s.UnlockedInsightIds.Add(t.Id);if(t.Id=="core:heaven_mind")DestinySystem.GrantTalentPoints(p,1);DestinySystem.ApplyEffectsToPlayer(p,t.Effect);return new ProgressionResult{Player=p,Success=true,Message=t.Id};}
    }

    public static class KarmaSystem
    {
        public static KarmaSystemState GetState(Player p)=>WorldState.Get(p,"karma",()=>new KarmaSystemState()); public static string GetAlignment(int karma)=>ProgressionUtil.Alignment(karma);
        public static string GetKarmaTitle(int k)=>k>=80?"righteousMaster":k>=50?"righteousExpert":k>=30?"righteousCultivator":k<=-80?"evilMaster":k<=-50?"evilExpert":k<=-30?"evilCultivator":"neutral";
        public static ProgressionResult ChangeKarma(Player p,int delta,string reason,string eventId=null){int before=p.Karma,next=ProgressionUtil.Clamp(before+delta,-100,100),actual=next-before;p.Karma=next;var s=GetState(p);s.TotalGained+=Math.Max(0,actual);s.TotalLost+=Math.Max(0,-actual);s.LastChangeAge=p.Age;if(eventId!=null)s.MajorEvents.Add(eventId);return new ProgressionResult{Player=p,Success=actual!=0,Alignment=GetAlignment(next),Title=GetKarmaTitle(next),Message=reason};}
    }
    public static class HeartDemonSystem
    {
        public static HeartDemonSystemState GetState(Player p)=>WorldState.Get(p,"heartDemon",()=>new HeartDemonSystemState());
        public static ProgressionResult AddHeartDemon(Player p,int amount,string source){var s=GetState(p);if(amount<=0)return new ProgressionResult{Player=p};if(s.SuppressedUntilAge.HasValue&&p.Age<s.SuppressedUntilAge.Value)amount=Math.Max(1,(int)Math.Floor(amount*.4));var a=ProgressionUtil.Alignment(p.Karma);if(a=="evil")amount=(int)Math.Ceiling(amount*1.25);if(a=="righteous")amount=Math.Max(1,(int)Math.Floor(amount*.85));int before=s.Value;s.Value=ProgressionUtil.Clamp(s.Value+amount,0,s.MaxValue);s.History.Insert(0,new HeartDemonHistory{Age=p.Age,Source=source,Outcome="gain",Value=s.Value});return new ProgressionResult{Player=p,Success=true,Triggered=s.Value>=60&&before<60,Message=source};}
        public static ProgressionResult TryHeartDemonTribulation(GameDatabase db,Player p,IRng rng,bool force=false){var s=GetState(p);double chance=s.Value<70?0:s.Value>=95?.45:s.Value>=85?.28:.14;if(s.SuppressedUntilAge.HasValue&&p.Age<s.SuppressedUntilAge.Value)chance=0;if(!force&&rng.NextDouble()>=chance)return new ProgressionResult{Player=p};int hp=Math.Max(20,(int)(p.MaxHp*(.45+s.Value/180.0)));var demon=new Combatant{Id="heart_demon",Name="heart_demon",RealmIndex=p.RealmIndex,Hp=hp,MaxHp=hp,Atk=Math.Max(1,(int)(p.Atk*(.75+s.Value/160.0))),Def=Math.Max(0,(int)(p.Def*(.6+s.Value/220.0))),Speed=p.Speed,CritRate=p.CritRate,CritDmgMultiplier=p.CritDmgMultiplier,CritResist=p.CritResist};var combat=CombatEngine.RunCombat(db,p,demon,rng,false);bool ok=combat.Winner=="player";s.LastTriggerAge=p.Age;if(ok){int reduce=Math.Min(s.Value,35+p.Comprehension/6);s.Value-=reduce;s.ConqueredCount++;p.Mood=Math.Min(100,p.Mood+10);EnlightenmentSystem.GainComprehension(p,Math.Max(8,reduce/2));}else{s.Value=Math.Min(s.MaxValue,s.Value+10);s.FailedCount++;s.ActiveDebuffs.Add(new HeartDemonDebuff{Id=$"heart-demon:{p.Age}:{s.FailedCount}",Name="heart_demon"});p.Hp=Math.Max(1,(int)Math.Floor(p.Hp*.75));p.Health=Math.Max(0,p.Health-12);p.Mood=Math.Max(0,p.Mood-15);}var r=new ProgressionResult{Player=p,Triggered=true,Success=ok,Message=combat.Winner};r.Logs.AddRange(combat.Logs);return r;}
    }

    public static class RankingSystem
    {
        public static readonly List<RankingDimensionDefRuntime> Dimensions=new(){Dim("core:realm_progress","realm",10,50),Dim("core:combat_power","power",20,50),Dim("core:wealth","wealth",30,50),Dim("core:reputation","reputation",40,50),Dim("core:technique_mastery","technique",50,50),Dim("core:heaven_chosen","destiny",10,30),Dim("core:prodigy","talent",20,30)};
        static RankingDimensionDefRuntime Dim(string id,string key,int order,int limit)=>new RankingDimensionDefRuntime{Id=id,Board=id.Contains("heaven")||id.Contains("prodigy")?"celestial":"leaderboard",ScoreKey=key,Order=order,Limit=limit};
        public static RankingSystemState GetState(Player p)=>WorldState.Get(p,"ranking",()=>new RankingSystemState());
        public static Player Refresh(GameDatabase db,Player p,bool force=false){var s=GetState(p);if(!force&&s.LastRefreshAge==p.Age)return p;s.Snapshots.Clear();foreach(var d in Dimensions)s.Snapshots[d.Id]=BuildSnapshot(db,p,d);s.LastRefreshAge=p.Age;return p;}
        public static RankingSnapshot BuildSnapshot(GameDatabase db,Player p,RankingDimensionDefRuntime d){var entries=BuildEntries(db,p,d);var snap=new RankingSnapshot{DimensionId=d.Id,RefreshedAtAge=p.Age,RefreshedAtYear=p.GameYear,RefreshedAtMonth=p.GameMonth};foreach(var e in entries.Take(d.Limit))snap.Entries.Add(e);var pe=entries.FirstOrDefault(e=>e.IsPlayer);snap.PlayerRank=pe?.Rank;snap.PlayerScore=pe?.Score??0;return snap;}
        public static List<RankingEntry> BuildEntries(GameDatabase db,Player p,RankingDimensionDefRuntime d){var list=new List<RankingEntry>{new RankingEntry{Id="player",Source="player",Name=p.Name,Emoji="player",RealmIndex=p.RealmIndex,Score=ScorePlayer(p,d.ScoreKey),IsPlayer=true}};foreach(var n in db.Npcs.Values)list.Add(new RankingEntry{Id=n.Id,Source="npc",Name=n.Name,Title=n.Title,Emoji=n.Emoji,RealmIndex=n.RealmIndex??0,Score=ScoreNpc(n,d.ScoreKey)});return list.OrderByDescending(e=>e.Score).ThenByDescending(e=>e.RealmIndex).ThenBy(e=>e.Id).Select((e,i)=>{e.Rank=i+1;return e;}).ToList();}
        public static int ScorePlayer(Player p,string key){if(key=="realm")return p.RealmIndex*100000+p.Exp;if(key=="power")return CalcPlayerPower(p);if(key=="wealth")return p.Gold+p.Inventory.Count*25+p.RealmIndex*500;if(key=="reputation")return p.Tracking.KillCount*8+p.Tracking.BossKillCount*80+AchievementSystem.GetState(p).UnlockedIds.Count*120+p.RealmIndex*150+p.Charisma*3;if(key=="technique")return p.Techniques.Sum(t=>t.Level*100+t.Exp);if(key=="destiny")return CalcPlayerPower(p)+p.Luck*40+p.Charisma*25;return p.Comprehension*45+p.Luck*30+p.Charisma*20+p.Techniques.Count*150+p.RealmIndex*300;}
        public static int CalcPlayerPower(Player p){var pv=PvpSystem.GetState(p);return (int)Math.Round(p.MaxHp*1.2+p.MaxMp*.7+p.Atk*18+p.Def*14+p.Speed*8+p.CritRate*10+p.CritResist*8+p.RealmIndex*1000+p.BodyRealmIndex*650+Math.Max(0,pv.Rating-1000)*.6);}
        static int ScoreNpc(NpcDef n,string key){int r=n.RealmIndex??0,c=n.Charisma??0,seed=Math.Abs((n.Id??"").GetHashCode());if(key=="realm")return r*100000+seed%50000;if(key=="power")return (int)Math.Round((n.Hp??0)*1.2+(n.Atk??0)*18+(n.Def??0)*14+(n.Speed??0)*8+(n.CritRate??0)*10+(n.CritResist??0)*8+r*1000);if(key=="wealth")return r*800+c*30+(n.Roles?.Count??0)*120+seed%700;if(key=="reputation")return r*120+c*4+(n.Roles?.Count??0)*100;if(key=="technique")return r*260+c*8+seed%450;if(key=="destiny")return r*1650+c*28+seed%1200;return r*420+c*34+seed%900;}
    }

    public static class PvpSystem
    {
        public static PvpSystemState GetState(Player p)=>WorldState.Get(p,"pvp",()=>new PvpSystemState());
        public static List<RankingEntry> GetCandidates(GameDatabase db,Player p){var snap=RankingSystem.BuildSnapshot(db,p,RankingSystem.Dimensions.First(d=>d.Id=="core:combat_power"));int pr=snap.PlayerRank??snap.Entries.Count+1;return snap.Entries.Where(e=>!e.IsPlayer&&e.Source=="npc"&&(Math.Abs(e.Rank-pr)<=12||Math.Abs(e.RealmIndex-p.RealmIndex)<=1)).Take(12).ToList();}
        public static PvpResult Challenge(GameDatabase db,Player p,string opponentId,IRng rng){var s=GetState(p);if(p.Age<s.CooldownUntilAge)return new PvpResult{Player=p,Success=false,Message="cooldown"};var entry=GetCandidates(db,p).FirstOrDefault(e=>e.Id==opponentId);if(entry==null||!db.Npcs.TryGetValue(opponentId,out var npc))return new PvpResult{Player=p,Success=false,Message="invalidOpponent"};var monster=NpcToCombatant(entry,npc);var combat=CombatEngine.RunCombat(db,p,monster,rng,false);bool won=combat.Winner=="player",draw=combat.Winner=="draw";p.Hp=Math.Max(1,combat.PlayerHpLeft);p.Mp=Math.Max(0,p.Mp-combat.MpUsed);int re=won?Math.Max(20,entry.Score/18):0,rg=won?Math.Max(10,20+entry.Rank*3):0;p.Exp+=re;p.Gold+=rg;int rd=won?Math.Max(12,(entry.Score-s.Rating)/40+25):draw?3:-18;s.Rating=Math.Max(100,s.Rating+rd);if(won)s.Wins++;else if(!draw)s.Losses++;s.CooldownUntilAge=p.Age+1;s.LastOpponentId=opponentId;var rec=new PvpDuelRecord{Id=$"pvp:{p.Age}:{s.Wins}:{s.Losses}",OpponentId=opponentId,OpponentName=entry.Name,OpponentRank=entry.Rank,PlayerWon=won,RewardExp=re,RewardGold=rg,Age=p.Age,Year=p.GameYear,Month=p.GameMonth};rec.Logs.AddRange(combat.Logs.Skip(Math.Max(0,combat.Logs.Count-8)));s.Records.Insert(0,rec);return new PvpResult{Player=p,Success=won,Message=combat.Winner,Record=rec,CombatResult=combat};}
        static Combatant NpcToCombatant(RankingEntry e,NpcDef n){double sc=1+Math.Max(0,e.Rank<=3?.18:e.Rank<=10?.08:0);return new Combatant{Id=n.Id,Name=n.Name,RealmIndex=n.RealmIndex??0,Hp=(int)Math.Round((n.Hp??1)*sc),MaxHp=(int)Math.Round((n.Hp??1)*sc),Atk=(int)Math.Round((n.Atk??1)*sc),Def=(int)Math.Round((n.Def??0)*sc),Speed=(int)Math.Round((n.Speed??0)*sc),MoveSpeed=Math.Max(5,n.Speed??0),CritRate=n.CritRate??0,CritDmgMultiplier=n.CritDmgMultiplier??1.5,CritResist=n.CritResist??0};}
    }

    public static class ReincarnationSystem
    {
        public const string ReincarnationOrbId="core:reincarnation_orb"; public static ReincarnationState GetState(Player p)=>WorldState.Get(p,"reincarnation",()=>new ReincarnationState());
        public static ReincarnationLegacy CalculateLegacyDelta(Player p,double m){int r=Math.Max(0,p.RealmIndex);double sc=1+r/10.0;return new ReincarnationLegacy{CultivationSpeedBonus=ProgressionUtil.Round2(.02*sc*m),BodyExpBonus=ProgressionUtil.Round2(.01*sc*m),AtkBonus=(int)Math.Ceiling(2*(1+r/5.0)*m),DefBonus=(int)Math.Ceiling(2*(1+r/5.0)*m),HpBonus=(int)Math.Ceiling(10*(1+r/3.0)*m),MpBonus=(int)Math.Ceiling(5*(1+r/3.0)*m),SpeedBonus=(int)Math.Ceiling(1*(1+r/8.0)*m),LuckBonus=(int)Math.Ceiling(2*m),ComprehensionBonus=(int)Math.Ceiling(2*m),CharismaBonus=(int)Math.Ceiling(2*m),AptitudeBonus=(int)Math.Ceiling(1*m),SpiritRootFloor=(int)Math.Ceiling(3*m),InventoryCapacityBonus=(int)Math.Ceiling(2*m),LifespanBonus=(int)Math.Ceiling(12*(1+r/5.0)*m)};}
        public static ReincarnationLegacy MergeLegacy(ReincarnationLegacy b,ReincarnationLegacy d)=>new ReincarnationLegacy{CultivationSpeedBonus=Math.Min(.5,ProgressionUtil.Round2(b.CultivationSpeedBonus+d.CultivationSpeedBonus)),BodyExpBonus=Math.Min(.3,ProgressionUtil.Round2(b.BodyExpBonus+d.BodyExpBonus)),AtkBonus=Math.Min(50,b.AtkBonus+d.AtkBonus),DefBonus=Math.Min(50,b.DefBonus+d.DefBonus),HpBonus=Math.Min(300,b.HpBonus+d.HpBonus),MpBonus=Math.Min(150,b.MpBonus+d.MpBonus),SpeedBonus=Math.Min(20,b.SpeedBonus+d.SpeedBonus),LuckBonus=Math.Min(20,b.LuckBonus+d.LuckBonus),ComprehensionBonus=Math.Min(20,b.ComprehensionBonus+d.ComprehensionBonus),CharismaBonus=Math.Min(20,b.CharismaBonus+d.CharismaBonus),AptitudeBonus=Math.Min(10,b.AptitudeBonus+d.AptitudeBonus),SpiritRootFloor=Math.Min(30,b.SpiritRootFloor+d.SpiritRootFloor),InventoryCapacityBonus=Math.Min(20,b.InventoryCapacityBonus+d.InventoryCapacityBonus),LifespanBonus=Math.Min(240,b.LifespanBonus+d.LifespanBonus)};
        public static ReincarnationCheck Check(Player p,string ctx){var s=GetState(p);double m=ctx=="death"?.5:1;bool can=!(ctx=="death"&&s.Count<1);string reason=can?"":"death_requires_prior";if(ctx=="voluntary"&&(p.RealmIndex<7||!InventorySystem.HasItem(p,ReincarnationOrbId))){can=false;reason="orbRequired";}var d=CalculateLegacyDelta(p,m);return new ReincarnationCheck{CanReincarnate=can,Reason=reason,Context=ctx,Multiplier=m,LegacyDelta=d,LegacyPreview=MergeLegacy(s.Legacy,d)};}
        public static ReincarnationResult Perform(GameDatabase db,Player old,string ctx,IRng rng,CreatePlayerOptions opt=null){var chk=Check(old,ctx);var res=new ReincarnationResult();if(!chk.CanReincarnate){res.NewPlayer=old;res.Logs.Add(chk.Reason);return res;}if(ctx=="voluntary")InventorySystem.RemoveItem(old,ReincarnationOrbId);var os=GetState(old);int count=os.Count+1;var np=PlayerFactory.CreatePlayer(db,opt??new CreatePlayerOptions{Name=old.Name,Gender=old.Gender,Appearance=old.Appearance,EnabledDLCs=old.EnabledDLCs.ToArray()},rng);np.DestinyId=old.DestinyId;foreach(var id in old.TalentIds)np.TalentIds.Add(id);np.Karma=(int)Math.Floor(old.Karma*.2);if(old.Systems.TryGetValue("achievement",out var ach))np.Systems["achievement"]=ach;if(old.Systems.TryGetValue("destiny",out var dest))np.Systems["destiny"]=dest;var ns=GetState(np);ns.Count=count;ns.Legacy=chk.LegacyPreview;ns.Snapshots.Add(new LegacySnapshot{IncarnationNo=count,PeakRealmIndex=old.RealmIndex,PeakBodyRealmIndex=old.BodyRealmIndex,Outcome=ctx=="ascension"?"ascended":ctx=="death"?"died":"voluntary",Age=old.Age});ApplyLegacyToPlayer(np,ns.Legacy);PlayerStatsSystem.RecalcStats(db,np);np.Hp=np.MaxHp;np.Mp=np.MaxMp;np.Stamina=np.MaxStamina;res.NewPlayer=np;res.Logs.Add($"reincarnation:{count}");res.LegacySnapshot=ns.Snapshots.Last();return res;}
        public static void ApplyLegacyToPlayer(Player p,ReincarnationLegacy l){p.Luck=Math.Min(100,p.Luck+l.LuckBonus);p.Comprehension=Math.Min(100,p.Comprehension+l.ComprehensionBonus);p.Charisma=Math.Min(100,p.Charisma+l.CharismaBonus);p.Lifespan+=l.LifespanBonus;p.InventoryCapacity+=l.InventoryCapacityBonus;foreach(var r in p.SpiritRoots.Roots)r.Affinity=Math.Max(r.Affinity,l.SpiritRootFloor);}
    }
    public static class AscensionSystem
    {
        public static AscensionState GetState(Player p)=>WorldState.Get(p,"ascension",()=>new AscensionState());
        public static AscensionDef GetAscensionForRealm(GameDatabase db,int realm)=>db.Ascensions.Values.FirstOrDefault(a=>(a.FromRealmIndex??-1)==realm);
        public static AscensionStatus GetStatus(GameDatabase db,Player p){var st=new AscensionStatus{IsLooseImmortal=p.Breakthrough.IsLooseImmortal};var def=GetAscensionForRealm(db,p.RealmIndex);st.AscDef=def;if(def==null){st.Missing.Add("noAscension");return st;}st.ExpReady=p.Exp>=(def.MinExp??0);if(!st.ExpReady)st.Missing.Add("exp");if(st.IsLooseImmortal)st.Missing.Add("looseImmortal");foreach(var c in def.ItemCosts??new List<ItemCountDef>())if(!InventorySystem.HasItem(p,c.ItemId,c.Count))st.Missing.Add(c.ItemId);foreach(var c in def.Conditions??new List<JToken>())if(!ProgressionUtil.CheckCondition(p,c))st.Missing.Add((string)c["id"]??"condition");st.CanAscend=!st.IsLooseImmortal&&st.Missing.Count==0;return st;}
        public static AscensionResult Attempt(GameDatabase db,Player p){var st=GetStatus(db,p);if(st.AscDef==null||!st.CanAscend)return new AscensionResult{Player=p,Success=false,AscDef=st.AscDef,Message="blocked"};foreach(var c in st.AscDef.ItemCosts??new List<ItemCountDef>())InventorySystem.RemoveItem(p,c.ItemId,c.Count);if(!string.IsNullOrEmpty(st.AscDef.TribulationId))return new AscensionResult{Player=p,Success=false,TriggerTribulation=true,TribulationId=st.AscDef.TribulationId,AscDef=st.AscDef};var ok=ApplySuccess(db,p,st.AscDef);return new AscensionResult{Player=ok.Player,Success=true,AscDef=st.AscDef,Message=ok.Message};}
        public static ProgressionResult ApplySuccess(GameDatabase db,Player p,AscensionDef def){p.RealmIndex=def.ToRealmIndex??p.RealmIndex;if((bool?)def.StatReset?["expReset"]==true)p.Exp=0;if(db.Realms.TryGetValue(p.RealmIndex,out var realm))p.Lifespan+=realm.LifespanBonus??0;p.Lifespan+=(int?)def.Rewards?["lifespanBonus"]??0;p.Exp+=(int?)def.Rewards?["bonusExp"]??0;foreach(var it in WorldJson.Objects(def.Rewards?["items"]))InventorySystem.AddItem(db,p,it.Value<string>("itemId"),it.Value<int?>("count")??1);var s=GetState(p);s.HasAscended=true;s.CurrentTier=def.ToTier;s.AscensionHistory.Add(new AscensionHistoryEntry{FromTier=def.FromTier,ToTier=def.ToTier,AtAge=p.Age,RealmIndexBefore=def.FromRealmIndex??p.RealmIndex});PlayerStatsSystem.RecalcStats(db,p);p.Hp=p.MaxHp;p.Mp=p.MaxMp;return new ProgressionResult{Player=p,Success=true,Message=def.Id};}
        public static ProgressionResult ApplyFailure(Player p,AscensionDef def){GetState(p).AscensionFailCount++;return new ProgressionResult{Player=p,Success=false,Message=def?.Id};}
    }

    public static class PrimordialEndgameSystem
    {
        public static PrimordialEndgameState GetState(Player p)=>WorldState.Get(p,"primordialEndgame",()=>new PrimordialEndgameState()); static string Route(Player p)=>p.Karma>=30?"righteous":p.Karma<=-30?"evil":"transcendent";
        public static ProgressionResult GetStatus(Player p){bool ok=p.RealmIndex>=15&&p.Exp>=520000000&&InventorySystem.HasItem(p,"cp-04:primordial_jade",3)&&string.IsNullOrEmpty(GetState(p).CompletedId);return new ProgressionResult{Player=p,Success=ok,Message=Route(p)};}
        public static ProgressionResult Attempt(GameDatabase db,Player p,IRng rng,bool skipCombat=false){var status=GetStatus(p);string route=Route(p);if(!status.Success)return status;InventorySystem.RemoveItem(p,"cp-04:primordial_jade",3);var s=GetState(p);string id="cp-04:endgame_"+route;if(!s.AttemptedIds.Contains(id))s.AttemptedIds.Add(id);var combat=skipCombat?new CombatResult{Winner="player",PlayerHpLeft=p.Hp}:CombatEngine.RunCombat(db,p,new Combatant{Id=id,Name="primordial_boss",RealmIndex=15,Hp=150000,MaxHp=150000,Atk=6000,Def=4000,Speed=1200,ExpReward=80000,GoldReward=12000},rng,false);if(combat.Winner!="player"){p.Hp=Math.Max(1,p.MaxHp/10);return new ProgressionResult{Player=p,Success=false,Message=combat.Winner};}p.Exp+=combat.ExpGained;p.Gold+=combat.GoldGained;p.Hp=Math.Max(1,combat.PlayerHpLeft);InventorySystem.AddItem(db,p,"cp-04:chaos_breath",3);s.CompletedId=id;s.EndingRoute=route;s.EndingTitle=route;s.EndingText=route;s.CompletedAtAge=p.Age;s.LegacyMultiplierBonus=.05;return new ProgressionResult{Player=p,Success=true,Completed=true,Message=id};}
    }

    public static class LearningSystem
    {
        public static LearningState GetState(Player p)=>WorldState.Get(p,"learning",()=>new LearningState()); public static int CalcActualStudyMonths(int b,int c)=>Math.Max(1,(int)Math.Ceiling(b*(100.0/(100+Math.Max(0,c)))));
        public static ProgressionResult StartStudy(GameDatabase db,Player p,string itemId){if(!db.Items.TryGetValue(itemId,out var scroll)||scroll.Category!="scroll")return new ProgressionResult{Player=p,Success=false,Message="notScroll"};if(!InventorySystem.HasItem(p,itemId))return new ProgressionResult{Player=p,Success=false,Message="itemMissing"};var s=GetState(p);if(s.ActiveStudy!=null)return new ProgressionResult{Player=p,Success=false,Message="alreadyStudying"};InventorySystem.RemoveItem(p,itemId);s.ActiveStudy=new ActiveStudy{ScrollItemId=itemId,ScrollType=scroll.ScrollType,TargetId=scroll.ScrollTargetId,TargetName=scroll.ScrollTargetId,TotalMonths=CalcActualStudyMonths(scroll.ScrollStudyMonths??1,p.Comprehension)};return new ProgressionResult{Player=p,Success=true,Message=s.ActiveStudy.TargetId};}
        public static ProgressionResult TickStudy(GameDatabase db,Player p,int months=1){var r=new ProgressionResult{Player=p};for(int i=0;i<months;i++){var s=GetState(p);if(s.ActiveStudy==null)break;s.ActiveStudy.ProgressMonths++;if(s.ActiveStudy.ProgressMonths>=s.ActiveStudy.TotalMonths){var c=CompleteStudy(db,p);r.Success=c.Success;r.Completed=c.Completed;r.Message=c.Message;break;}}return r;}
        public static ProgressionResult CompleteStudy(GameDatabase db,Player p){var s=GetState(p);var st=s.ActiveStudy;if(st==null)return new ProgressionResult{Player=p,Success=false,Message="noActiveStudy"};if(st.ScrollType=="technique"){if(!p.Techniques.Any(t=>t.TechniqueId==st.TargetId))p.Techniques.Add(new TechniqueSlot{TechniqueId=st.TargetId,Level=1,Exp=0,InstanceId=st.TargetId});}else if(st.ScrollType=="divineArt")DivineArtSystem.Learn(db,p,st.TargetId);else if(st.ScrollType=="recipe")s.LearnedRecipes=s.LearnedRecipes.Concat(new[]{st.TargetId}).Distinct().ToArray();else s.LearnedSmithingRecipes=s.LearnedSmithingRecipes.Concat(new[]{st.TargetId}).Distinct().ToArray();s.ActiveStudy=null;return new ProgressionResult{Player=p,Success=true,Completed=true,Message=st.TargetId};}
    }

    public static class AchievementSystem
    {
        static readonly List<AchievementDefRuntime> Achievements=new(){Ach("core:first_blood",new Dictionary<string,double>{{"atk",1}}),Ach("core:qi_condensation",new Dictionary<string,double>{{"maxHp",10}}),Ach("core:first_gold",new Dictionary<string,double>{{"luck",1}}),Ach("core:technique_scholar",new Dictionary<string,double>{{"atk",5},{"def",5}})};
        static AchievementDefRuntime Ach(string id,Dictionary<string,double> bonus){var a=new AchievementDefRuntime{Id=id,Name=id,Category="core"};foreach(var kv in bonus)a.BonusStats[kv.Key]=kv.Value;return a;}
        public static AchievementSystemState GetState(Player p)=>WorldState.Get(p,"achievement",()=>new AchievementSystemState()); public static List<AchievementDefRuntime> GetAllAchievements()=>Achievements.ToList();
        public static ProgressionResult CheckAchievements(Player p){var s=GetState(p);var newly=new List<string>();foreach(var a in Achievements){if(s.UnlockedIds.Contains(a.Id))continue;bool ok=a.Id=="core:first_blood"?p.Tracking.KillCount>=1:a.Id=="core:qi_condensation"?p.RealmIndex>=1:a.Id=="core:first_gold"?p.Gold>=100:a.Id=="core:technique_scholar"?p.Techniques.Count>=3:false;if(!ok)continue;s.UnlockedIds.Add(a.Id);s.PendingToast.Add(a.Id);newly.Add(a.Id);foreach(var kv in a.BonusStats)if(kv.Key=="luck"||kv.Key=="comprehension"||kv.Key=="charisma"||kv.Key=="lifespan")ProgressionUtil.AddStat(p,kv.Key,kv.Value);}return new ProgressionResult{Player=p,Success=newly.Count>0,Message=string.Join(",",newly)};}
        public static StatEffect GetRecalcBonus(Player p){var e=new StatEffect();foreach(var id in GetState(p).UnlockedIds){var a=Achievements.FirstOrDefault(x=>x.Id==id);if(a==null)continue;foreach(var kv in a.BonusStats)if(!(kv.Key=="luck"||kv.Key=="comprehension"||kv.Key=="charisma"||kv.Key=="lifespan"))e.StatBonuses[kv.Key]=(e.StatBonuses.TryGetValue(kv.Key,out var v)?v:0)+kv.Value;}return e;}
    }

    public static class ChronicleSystem
    {
        public static CultivationChronicle Empty()=>new CultivationChronicle();
        public static CultivationChronicle CreateIncarnation(GameDatabase db,Player p,CultivationChronicle c){var rec=new IncarnationRecord{IncarnationNo=c.NextIncarnationNo++,CharacterName=p.Name,CharacterGender=p.Gender,StartedAt=p.Age,FinalRealmIndex=p.RealmIndex,FinalBodyRealmIndex=p.BodyRealmIndex,FinalRealmName=db.Realms.TryGetValue(p.RealmIndex,out var r)?r.Name:"realm",PeakExp=p.Exp,FinalAge=p.Age,FinalLifespan=p.Lifespan,TotalKills=p.Tracking.KillCount};c.Current=rec;return c;}
        public static CultivationChronicle AddEvent(CultivationChronicle c,ChronicleEvent e){if(c.Current!=null)c.Current.Events.Add(e);return c;}
        public static CultivationChronicle UpdateCurrentSnapshot(GameDatabase db,CultivationChronicle c,Player p){if(c.Current==null)return c;c.Current.FinalRealmIndex=p.RealmIndex;c.Current.PeakExp=Math.Max(c.Current.PeakExp,p.Exp);c.Current.FinalAge=p.Age;c.Current.TotalKills=p.Tracking.KillCount;return c;}
        public static CultivationChronicle FinalizeIncarnation(GameDatabase db,CultivationChronicle c,Player p,string outcome){if(c.Current==null)return c;UpdateCurrentSnapshot(db,c,p);c.Current.Outcome=outcome;c.Current.Events.Add(new ChronicleEvent{Type="game_over",Year=p.GameYear,Month=p.GameMonth,Description=outcome});c.Incarnations.Add(c.Current);c.Current=null;return c;}
    }
}
